apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteMany 
  nfs:
    server: 9.115.17.155
    path: /var/nfs-data/pv01
  persistentVolumeReclaimPolicy: Recycle  
