apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv02
spec:
  capacity:
    storage: 10Gi 
  accessModes:
  - ReadWriteMany 
  nfs:
    server: 9.115.17.155
    path: /var/nfs-data/pv02
  persistentVolumeReclaimPolicy: Recycle  
